reading:
  rgb_regex: (.+)\.tif
  uv_regex: (.+)uv\.tif
  uv_channel_index: 0

  extensions: [.jpg]
  ordered: false

segmentation:
  # method: "grabcut+otsu"
  # grabcut+otsu, grabcut, otsu, flatbug, unet
  method: "flatbug"
  channel: saturation
  rescale: 0.5
  ksize: null # no smoothing
  fill_holes: False


calibration:
  enabled: True
  max_corners: 50
  roi_fraction: 0.15
  square_size: 1.0 # in mm
  position: null # position of the scalebar in the image
  template_path: scalebar_template.jpg
  template_scale: 290.0 # in pixels per mm

points_of_interest:
  enabled: True

execution:
  # if False, the asks for confirmation before proceeding
  # can be overriden by the command line argument --yes/-y
  proceed: True
  # if True, the results are overwritten without asking
  # can be overriden by the command line argument --force/-f
  force: True
